== Custom User Standalone XML Configuration
= Usage

To provide custom configurations you must:
1. Create a config map containing at least `standalone.xml` which is mounted at `/opt/datagrid/standalone/configuration/user`
2. Set the environment variable `USER_CONFIG_MAP=true` in your template
3. Expose the required services and ports in your template

When `USER_CONFIG_MAP=true` our image copies the contents of `opt/datagrid/standalone/configuration/user`. i.e. the configmap, to `/opt/datagrid/standalone/configuration`.
This means that in addition to passing `standalone.xml`, it is also possible to provide `logging.properties`, `application-role.properties` etc in the configmap.

Creating a configmap containing the desired configuration files is trivial, as an entire directory can be used to create a configmap consisting of filenames and their contents as key/values in the configmap. This can be achieved via `oc create configmap <name-of-configmap> --from-file=<local-dir>`.

To create an application that uses a custom configuration, login to your openshift cluster via `oc`, push your built image to the cluster's repository and execute the following:

1. `oc create -f templates/datagrid72-user-xml.json`
2. `oc create configmap datagrid-config --from-file=docs/examples/user-configuration`
3. `oc new-app user-xml`

The server should then startup with the provided configuration files.

= Example Template
`templates/datagrid72-user-xml.json` is a basic template that shows how a config map can be created and the `USER_CONFIG_MAP` should be set.
Furthermore, this template exposes the ports required for the ping, hotrod and rest protocols.

NOTE: If using openshift.DNS_PING protocol for JGroups discovery (recommended) it's also necessary to set the ENV variable `OPENSHIFT_DNS_PING_SERVICE_NAME` to the name of the ping service
and `OPENSHIFT_DNS_PING_SERVICE_PORT` to the exposed port.

= Image Env Variables
In the provided link:examples/user-configuration/standalone.xml[standalone.xml] we have included several comments beginning and ending with `##`, e.g. `<!-- ##JGROUPS_ENCRYPT## -->`.
If you keep these comments in your `standalone.xml` file, then it remains possible to use some of the images environment variables
for more complicated tasks such as enabling encryption in JGroups. Environment variables related infinispan caches
and endpoints no longer work when providing a configuration via a configmap, therefore all cache/endpoint configuration
has to occur in your `standalone.xml` file.

NOTE: It is possible to remove the aforementioned xml comments, however it will result in certain environment variables
being ignored.
