= Custom User Standalone XML Configuration

== Providing Custom Configuration

Do the following:

1. Mount `standalone.xml` at `/opt/datagrid/standalone/configuration/user`.
2. Set the environment variable `USER_CONFIG_MAP=true` in your template.
3. Expose the required services and ports in your template.

If `USER_CONFIG_MAP=true`, Data Grid copies the contents of `opt/datagrid/standalone/configuration/user` to `/opt/datagrid/standalone/configuration`. As a result, you can also provide `logging.properties`, `application-role.properties`, and so on in the ConfigMap.

== Creating Custom Data Grid Applications

Do the following:

1. `oc create -f docs/examples/user-configuration/user-config-template.yaml`
2. `oc create configmap datagrid-config --from-file=docs/examples/user-configuration`
3. `oc new-app user-config`

Your Data Grid for OpenShift cluster starts with the configuration files from the ConfigMap.

= Example Template

link:examples/user-configuration/user-config-template.yaml[examples/user-configuration/user-config-template.yaml] illustrates how to create a ConfigMap and set `USER_CONFIG_MAP`.

`user-config-template.yaml` also exposes ports for the ping, hotrod, and rest protocols.

**NOTE:** If you use the `openshift.DNS_PING` protocol for cluster discovery (recommended), you must set the following environment variables:

* `OPENSHIFT_DNS_PING_SERVICE_NAME` specifies the name of the ping service.
* `OPENSHIFT_DNS_PING_SERVICE_PORT` specifies the exposed port.

= Image Environment Variables
link:examples/user-configuration/standalone.xml[examples/user-configuration/standalone.xml] includes several comments that begin and end with two # signs, for example:

```
<!-- ##JGROUPS_ENCRYPT## -->
```

These comments act as placeholders for environment variables. Keep these comments in `standalone.xml` to use environment variables for configuration tasks such as enabling JGroups encryption. If you remove the comments, certain environment variables no longer take effect.

Likewise, environment variables related to Infinispan caches and endpoints do not take effect when using custom server configuration via a ConfigMap. For this reason, your `standalone.xml` file must contain all cache/endpoint configuration.

For more information about creating custom configuration, see link:https://access.redhat.com/documentation/en-us/red_hat_data_grid/7.3/html-single/red_hat_data_grid_for_openshift/index#os_custom_xml[Applying Custom Configuration through the ConfigMap API] in the _Red Hat Data Grid for OpenShift_ documentation.
